### PR TITLE
Adding @EnvironmentVariable wrapper

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Hey :))
This is a simple one, just adds a property wrapper to get and set the system's env vars.

### CODE REVIEW

**Comment by guillermomuntaner** [comment]
Hey @LucianoPAlmeida, thanks for contributing.

It looks already really good to me, just want to discuss couple more ideas:
1. Do you think is useful to expose the setter? It could be read only too.
2. I understand you went with the Foundation API for reading since it is available and went lower level for writing. I am just wondering if it would be nicer to use same API for both getter & setter. By using `getenv` we could drop Foundation and use Glibc to make this available also in Linux.

Looking forward to hearing your thoughts.
Regards.

**Comment by LucianoPAlmeida** [comment]
Hey @guillermomuntaner :))
> 1. Do you think is useful to expose the setter? It could be read-only too.
I'm not sure if it's useful, personally most of the times I just read them. But I thought will not hurt to leave a set as an option since is very simple to implement. But I could make read-only no problem :) 

> 2. I understand you went with the Foundation API for reading since it is available and went lower level for writing. I am just wondering if it would be nicer to use the same API for both getter & setter. By using `getenv` we could drop Foundation and use Glibc to make this available also in Linux.
I think this is available on CoreLibs Foundation too([here](https://github.com/apple/swift-corelibs-foundation/blob/7b72fbd766b8e5934f505bacc973ce4e8e3938ab/Foundation/ProcessInfo.swift#L37)), so use this API will work on Linux as well. I just choose that for simplicity, but now that you mention maybe we use the low level on getter too for consistency. 
I'm making the changes 👍

**Comment by guillermomuntaner** [comment]
Yeah I saw the port of ProcessInfo in CoreLibs Foundation, but I am really unaware of the status of the whole project and other platform support in general. This can be worked out later since lots of other pieces missing for Linux support anyways.

One last request though; could you update the cocoapods podspec with a new submodule? 
I forgot to add that one to the contrib guidelines, sorry about that.

Thanks a lot!

**Comment by LucianoPAlmeida** [comment]
> Yeah I saw the port of ProcessInfo in CoreLibs Foundation, but I am really unaware of the status of the whole project and other platform support in general. This can be worked out later since lots of other pieces missing for Linux support anyways.

Sure :)) 

> One last request though; could you update the cocoapods podspec with a new submodule?
> I forgot to add that one to the contrib guidelines, sorry about that.

Done 👍

**Comment by guillermomuntaner** [comment]
Thanks a lot :)

**Pull request merged**
